name: py2AI
dependencies:
- openssl=1.0.2g=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- setuptools=20.3=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - canvasvg==1.0.0
  - pmw==2.0.1
  - tkintertable==1.2

